### ISSUE TITLE
Warning message: In for (i in seq_len(n)) { :

### ISSUE THREAD

**Issue by iagojunger** [GenomicSEM/GenomicSEM#35]
Hello, dear Nivard!
        I’m a beginner in coding and R language. Resuming, I need to complete a LDSC between two traits to continue my project. So, I started by using your wiki about the procedure of running multivariate LDSC.
	The first step,munge, apparently worked. 

munge(c("data1/adhd.sumstats.txt", "data1/depression.sumstats.txt"), "data1/w_hm3.noMHC.snplist",trait.names=c("adhd", "depression"), c(55374, 500199), info.filter = 0.9, maf.filter = 0.01)

Nevertheless, when I runned the LDSC this error occured :

traits <- c("adhd.sumstats.gz", "depression.sumstats.gz")
sample.prev <- c(.36,.34)
population.prev <- c(.025,.07)
ld <- "eur_w_ld_chr/"
wld <- "eur_w_ld_chr/"
trait.names<-c("adhd","depression")
LDSCoutput <- ldsc(traits=traits, sample.prev=sample.prev, population.prev=population.prev, ld=ld, wld=wld, trait.names=trait.names)

_Warning message:
In for (i in seq_len(n)) { :
  closing unused conection 3 (adhd_depression_munge.log)_

And I doesn’t know where I screwed up, I wish you could help me :)

All the best,

Iago

 
![image](https://user-images.githubusercontent.com/76215768/107035795-6eb4d700-6797-11eb-899d-185c82cf6e61.png)

**Comment by agrotzin** [comment]
Hi Iago, 

Apologies for the late reply, we are generally quicker if you post on the google group (https://groups.google.com/u/1/g/genomic-sem-users). My initial suggestions would be to check the .log file to see if anything more informative is printed there, but nothing stands out as wrong there. If you are still having issues please follow up on the google group and am happy to troubleshoot further. 

Best,  
  Andrew
