### ISSUE TITLE
Munge Issue

### ISSUE THREAD

**Issue by gz344** [GenomicSEM/GenomicSEM#36]
Hi there,

I am trying to run the munge step using my summary statistics but I am stuck with this error message:

 ''Error in fread(hm3, header = T, data.table = F) : 
  File 'w_hm3.snplist' is a directory. Not yet implemented.
In addition: Warning message:
In for (i in seq_along(col)) col[i] <- length(scan(file, what = "",  :
  closing unused connection 3 (ADHD_2017_EduYears_Main.LDSC_Income_munge.log)''

Does anyone know what does this mean and how can I resolve it ?

Thank you in advance,

Gina

**Comment by agrotzin** [comment]
Hi Gina, 

It looks like munge is unable to find the hapmap3 SNP list you are using. You'll want to make sure that SNP list is either in the same directory as the GWAS summary statisitcs that you are munging, or that you specify the appropriate file path to that SNP list for the hm3 argument in munge. 

-Andrew

**Comment by Gina93** [comment]
Thank you very much for your help Andrew!

I am doing a mediation analysis using Genomic-SEM for my dissertation and I am confused regarding which values I should report in the result section? Also, the output I get from R includes only the estimates (standardized and unstardardized) and the standard errors. How do I know if the effects (indirect,direct and total) are significant or non-significant?

PS: Apologies in advance if the questions seem silly, but this is the first time I am working with this type of analysis and I am really confused.

Thank you in advance,
Gina

**Comment by tuckerdrob** [comment]
Hi Gina,
You could create a new model parameter representing the indirect effect.
You already have the direct effect  from teh model, and this would give you
the indirect effect. You could also create a new parameter representing the
total effect (direct + indirect) and even one that represents the
proportion of the total effect that is mediated. This is standard SEM
stuff, so you can just check out the lavaan tutorial on how to do that
https://lavaan.ugent.be/tutorial/mediation.html
You can see standard (non genetic) SEM mediation papers that have been
published in your area of study to see what the conventions are for
reporting mediation.
All the best,
Elliot

**Comment by agrotzin** [comment]
Hi Gina, 

The code below using strsplit from the stringr package should work 

data$SNP<-sapply(strsplit(data$SNP, ":"), `[`, 1)

Best, 
  Andrew

**Comment by Gina93** [comment]
Hi Andrew,
I tried that and I got this error:

 data$SNP<-sapply(strsplit(data$SNP, ":"), [, 1)
Error: unexpected '[' in "data$SNP<-sapply(strsplit(data$SNP, ":"), ["

Am I doing something wrong?

Thank you,
Gina

**Comment by agrotzin** [comment]
The dataset needs to be called data and the SNP column name called SNP for that to work so you'll want to make sure those pieces are changed to reflect the dataset you are using. You'll also want to make sure the stringr package is loaded. Beyond that the code should work.
