### ISSUE TITLE
GWAS-by-subtraction: how to calculate the contribution of latent factor to the outcome?

### ISSUE THREAD

**Issue by WeiCSong** [GenomicSEM/GenomicSEM#37]
Hi, thanks for the great tool! I read in your NG paper abstract about "noncog accounts for 57%  genetic variance of EA" but seems that the calculation of this statistic is not mentioned in the main text. I also read the tutorial at https://rpubs.com/MichelNivard/565885 and failed to find this step. Could you tell me where to find the code for this step? Thank you very much for your help!

**Comment by tuckerdrob** [comment]
There is a full derivation under " Model and parameter specification in
terms of the observed moments" in the supplement. But simply put, total
variance in EA is sum of the respective contributions of cog and noncog,
i.e. lambda_cogEA^2+lambda_noncogEA^2 when cog and noncog have variances of
1.0 (as they do in the rpubs figure). The proportional contributions of
each component to total genetic variance is the squared lambda for that
component over the sum of the squared lambdas.
Best regards,
Elliot

**Comment by WeiCSong** [comment]
Got it, thanks a lot!
