### ISSUE TITLE
Tissue and cell-type enrichment [Feature Request]

### ISSUE THREAD

**Issue by mglev1n** [GenomicSEM/GenomicSEM#41]
Stratified LD score regression has been extended to evaluate tissue and cell-type enrichment (see: [Finucane et al. 2018 Nat Genet.](https://www.nature.com/articles/s41588-018-0081-4) and https://github.com/bulik/ldsc/wiki/Cell-type-specific-analyses). From what I can tell this is not currently supported in GenomicSEM, but may be a useful addition for evaluating the tissues and cell types relevant to latent factors in a model. Right now, the alternative (and slower) approach seems like running a GWAS of the latent factors (eg. https://github.com/GenomicSEM/GenomicSEM/wiki/5.-User-Specified-Models-with-SNP-Effects), and then using those summary statistics within the original ldsc python tool.

**Comment by tuckerdrob** [comment]
This capability within Genomic SEM is documented here: https://github.com/GenomicSEM/GenomicSEM/wiki/6.-Stratified-Genomic-SEM

We would recommend against applying univariate s-ldsc to sumstats from multivariate GWAS (e.g. common factor GWAS), as that approach does not formally distinguish between enrichment of general and trait-specific genetic effects. As you also note, such an approach is computationally less efficient.

You can read more about stratified Genomic SEM in the following two preprints:

Grotzinger, A. D., …Tucker-Drob, E. M., & Nivard, M. G. (2020). Genetic architecture of 11 major psychiatric disorders at biobehavioral, functional genomic, and molecular genetic levels of analysis. medRχiv [Tucker-Drob & Nivard jointly directed this work] Link (to preprint)

Grotzinger, A. D., de la Fuente, J., Davies, G., Nivard, M. G., & Tucker-Drob, E. M. (2021). Transcriptome-wide and stratified genomic structural equation modeling identify neurobiological pathways underlying general and specific cognitive functions. medRχiv. Link (to preprint)

You may also be interested in Transcriptome-wide SEM (T-SEM), described in the the second preprint listed above, and here: https://github.com/GenomicSEM/GenomicSEM/wiki/7.-Transcriptome-wide-SEM-(T-SEM)
