### ISSUE TITLE
Issue with commonfactorGWAS

### ISSUE THREAD

**Issue by bkupmc** [GenomicSEM/GenomicSEM#50]
I am getting the following error:
Error in nrow(SNPs) : object 'SNPs' not found

This call is made at line 205:
if (cores > nrow(SNPs))

SNPs has been removed by that point. To solve this use SNPs2 instead of SNPs

Bert Klei
Computational Genetics
WPH-UPMC

**Comment by agrotzin** [comment]
Thanks for pointing this out! Just put in the fix.
