### ISSUE TITLE
Mislabelled columns in GenomicSEM/R/utils.R

### ISSUE THREAD

**Issue by LizaDarrous** [GenomicSEM/GenomicSEM#54]
Hello,

I noticed that when my column heads have ALT and REF as the allele columns, munging them in GenomicSEM will assign REF to A1 and ALT to A2 causing a flip in effect and genetic correlation later on. I tracked it down to lines 11-12 in (https://github.com/GenomicSEM/GenomicSEM/tree/master/R)/utils.R where REF is included in the possible alternate column names for A1 but not ALT, and both ALT and REF are included in the possible alternate names for A1.
Thanks for all your help!

**Comment by MichelNivard** [comment]
Ha, that sounds like a bug to me; we'll look into it and fix asap.

**Comment by matthijsz** [comment]
Thanks bringing this to our attention, and thanks for your detailed investigation on the source of the issue! 

It should be fixed now, REF will still be interpreted as A1, and ALT as A2, but if both REF and ALT are present in the summary statistics file GenomicSEM will now present (and log) a message informing you how these are interpreted to prevent confusion from flipped effects later on. 

If they should be interpreted in reverse (i.e. if ALT is A1 and REF is A2 in your case) you can either rename them in the base files, or use the `column.names` argument in `munge()`:  `munge(files, ..., column.names=list(A1="ALT", A2="REF") )`

**Comment by LizaDarrous** [comment]
Hi,
Thanks for the quick fix!! Don't know if it's possible to change it so that ALT is A1 by default and REF is A2 as this is the most common nomenclature in genetics/GWAS studies? 
But indeed, there's always a way around. Thanks!
