### ISSUE TITLE
sumstats() error when merging with ref after dplyr update

### ISSUE THREAD

**Issue by mja** [GenomicSEM/GenomicSEM#63]
The `sumstats()` function started producing the error

```r
Error in `inner_join()`:
! `...` must be empty.
✖ Problematic arguments:
• all.x = F
• all.y = F
```
which comes from line:
https://github.com/GenomicSEM/GenomicSEM/blob/dbe713c28c63d38739852a9aadb783dae71f2c41/R/sumstats_main.R#L74

Seems to be from the new `join_by` syntax in [dplyr 1.1.0](https://dplyr.tidyverse.org/news/index.html#new-features-1-1-0), where in previous versions of dplyr, the spurious `all.x=F,all.y=F` would be swallowed up and ignored by the `...` parameter in `inner_join()`; they now cause an error.

**Comment by mja** [comment]
There's another instance that I missed in my PR:

https://github.com/GenomicSEM/GenomicSEM/blob/17a01e80104c0af63c99a09de316f45fe467161d/R/sumstats.R#L122

**Comment by agrotzin** [comment]
Thanks for raising this Mark! Should be fixed now.
