### ISSUE TITLE
error when run usermodel

### ISSUE THREAD

**Issue by dqq0404** [GenomicSEM/GenomicSEM#78]
Hi,
When I used the usermodel parameter as below：
usermodel(LDSCoutput, estimation = "DWLS", model = CFAofEFA, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)
and was wrong:
Error in usermodel(LDSCoutput, estimation = "DWLS", model = CFAofEFA,  : 
  object 'ReorderModel' not found
What should I do to fix it?

**Comment by tuckerdrob** [comment]
Check your model syntax for a misspelled variable name or stray typo.
