### ISSUE TITLE
Error in Multivariate GWAS

### ISSUE THREAD

**Issue by dqq0404** [GenomicSEM/GenomicSEM#79]
Hi,
When I run User Specified Models with SNP Effects, I get an error : object 'SNPs2' not found.
What can I do to fix it?

**Comment by dqq0404** [comment]
When I set the core parameter, it was solved.

**Comment by sam-white04** [comment]
I had the same issue, and setting the core parameter fixed it. Weird. But, thank you for the helpful post.
